package github.com.hukuta94.delivery.core.domain

import java.util.*

/**
 * Domain Event
 * These events are generated by core in domain layer.
 * ID is computed when instance is being creating.
 *
 * Domain events are used inside application and can be sent to
 * external services by mapping into specific transport protocol.
 *
 * Integration Domain Event
 * These events are generated by other bounded contexts (external services/applications).
 *
 * Integration events are used to cross boundary from external services into our application.
 * ID of integration event is provided by external service that we could identify events that we processed already.
*/
abstract class DomainEvent {
    val eventId: UUID = UUID.randomUUID()
}