delivery:
  # spring-jpa | ktorm | inmemory
  orm: spring-jpa
  relay:
    # Number of inbox/outbox messages fetched and processed per relay run.
    batch-size: 50

  cors:
    allowed-origins:
      - http://localhost:8086
    allowed-methods:
      - GET
      - POST

  grpc:
    geo:
      address: localhost
      port: 8084

server:
  port: 8080

spring:
  application:
    name: delivery application

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET SESSION idle_in_transaction_session_timeout = '10000'"

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      properties:
        max.block.ms: 5000
        enable.idempotence: true
        request.timeout.ms: 5000
        delivery.timeout.ms: 7000