package github.com.hukuta94.delivery.core.domain

import java.util.*

/**
 * These events are generated by other bounded contexts (external services/applications).
 *
 * Integration events are used to cross boundary from external services into our application.
 * ID of integration event is provided by external service that we could identify events that we processed already.
 */
open class IntegrationEvent protected constructor(id: UUID): DomainEvent(id)